export const advisor = { name: "Dana Reyes", title: "CFP" };

export const clients = [
  {
    id: 1,
    name: "Eleanor Voss",
    email: "eleanor.voss@email.com",
    phone: "(312) 555-0182",
    riskTier: "Growth",
    portfolioValue: 487500,
    products: ["Mutual Funds", "ETFs", "IRA"],
    lastContact: "2026-08-17",
    status: "Active",
  },
  {
    id: 2,
    name: "Marcus Webb",
    email: "marcus.webb@email.com",
    phone: "(312) 555-0247",
    riskTier: "Aggressive",
    portfolioValue: 1240000,
    products: ["Options", "Stocks", "401(k)"],
    lastContact: "2026-08-17",
    status: "Active",
  },
  {
    id: 3,
    name: "Priya Anand",
    email: "priya.anand@email.com",
    phone: "(312) 555-0391",
    riskTier: "Conservative",
    portfolioValue: 320000,
    products: ["Bonds", "CDs", "Roth IRA"],
    lastContact: "2026-08-19",
    status: "Active",
  },
  {
    id: 4,
    name: "Roland Kim",
    email: "roland.kim@email.com",
    phone: "(312) 555-0128",
    riskTier: "Growth",
    portfolioValue: 675000,
    products: ["ETFs", "Mutual Funds", "Rollover IRA"],
    lastContact: "2026-08-10",
    status: "Active",
  },
  {
    id: 5,
    name: "Sofia Duarte",
    email: "sofia.duarte@email.com",
    phone: "(312) 555-0473",
    riskTier: "Growth",
    portfolioValue: 215000,
    products: ["529 Plan", "ETFs"],
    lastContact: "2026-08-20",
    status: "Active",
  },
  {
    id: 6,
    name: "Harold Given",
    email: "harold.given@email.com",
    phone: "(312) 555-0562",
    riskTier: "Conservative",
    portfolioValue: 890000,
    products: ["Bonds", "Annuity", "IRA"],
    lastContact: "2026-08-14",
    status: "Active",
  },
  {
    id: 7,
    name: "Nadia Farrow",
    email: "nadia.farrow@email.com",
    phone: "(312) 555-0635",
    riskTier: "Aggressive",
    portfolioValue: 0,
    products: [],
    lastContact: "2026-08-18",
    status: "Prospect",
  },
];

export const appointments = [
  {
    id: 1,
    clientId: 1,
    clientName: "Eleanor Voss",
    date: "2026-08-17",
    time: "10:00 AM",
    type: "Portfolio review",
    riskTier: "Growth",
    notes: "Q3 rebalancing discussion",
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Marcus Webb",
    date: "2026-08-17",
    time: "2:30 PM",
    type: "Options strategy call",
    riskTier: "Aggressive",
    notes: "Review covered call positions",
  },
  {
    id: 3,
    clientId: 7,
    clientName: "Nadia Farrow",
    date: "2026-08-18",
    time: "4:00 PM",
    type: "New account funding",
    riskTier: "Aggressive",
    notes: "Initial funding $150k",
  },
  {
    id: 4,
    clientId: 3,
    clientName: "Priya Anand",
    date: "2026-08-19",
    time: "9:00 AM",
    type: "Annual review",
    riskTier: "Conservative",
    notes: "Beneficiary update needed",
  },
  {
    id: 5,
    clientId: 5,
    clientName: "Sofia Duarte",
    date: "2026-08-20",
    time: "1:00 PM",
    type: "529 plan setup",
    riskTier: "Growth",
    notes: "College savings for daughter age 6",
  },
  {
    id: 6,
    clientId: 4,
    clientName: "Roland Kim",
    date: "2026-08-21",
    time: "11:00 AM",
    type: "Rollover review",
    riskTier: "Growth",
    notes: "401k to IRA rollover final steps",
  },
  {
    id: 7,
    clientId: 6,
    clientName: "Harold Given",
    date: "2026-08-22",
    time: "3:00 PM",
    type: "Estate planning",
    riskTier: "Conservative",
    notes: "Coordinate with estate attorney",
  },
];

export const followUps = [
  {
    id: 1,
    clientId: 1,
    clientName: "Eleanor Voss",
    task: "Confirm risk tolerance after review.",
    status: "Scheduled",
    dueDate: "2026-08-18",
    appointmentId: 1,
  },
  {
    id: 2,
    clientId: 2,
    clientName: "Marcus Webb",
    task: "Discuss options strategy paperwork.",
    status: "Scheduled",
    dueDate: "2026-08-18",
    appointmentId: 2,
  },
  {
    id: 3,
    clientId: 3,
    clientName: "Priya Anand",
    task: "Send annual review summary.",
    status: "Follow-up sent",
    dueDate: "2026-08-17",
    appointmentId: null,
  },
  {
    id: 4,
    clientId: 4,
    clientName: "Roland Kim",
    task: "Share rollover confirmation.",
    status: "Follow-up sent",
    dueDate: "2026-08-17",
    appointmentId: null,
  },
  {
    id: 5,
    clientId: 5,
    clientName: "Sofia Duarte",
    task: "Set up 529 beneficiary.",
    status: "Scheduled",
    dueDate: "2026-08-19",
    appointmentId: 5,
  },
  {
    id: 6,
    clientId: 6,
    clientName: "Harold Given",
    task: "Draft estate planning notes.",
    status: "Completed",
    dueDate: "2026-08-15",
    appointmentId: null,
  },
];

export const pipelineDeals = [
  {
    id: 1,
    clientName: "Nadia Farrow",
    value: 150000,
    product: "New Account",
    stage: "Proposal",
    probability: 80,
    nextAction: "Funding paperwork",
    dueDate: "2026-08-20",
  },
  {
    id: 2,
    clientName: "James Okoye",
    value: 500000,
    product: "Managed Portfolio",
    stage: "Discovery",
    probability: 40,
    nextAction: "Risk assessment call",
    dueDate: "2026-08-22",
  },
  {
    id: 3,
    clientName: "Linda Chu",
    value: 250000,
    product: "IRA Rollover",
    stage: "Negotiation",
    probability: 90,
    nextAction: "Final paperwork",
    dueDate: "2026-08-19",
  },
  {
    id: 4,
    clientName: "Carlos Ruiz",
    value: 75000,
    product: "529 Plan",
    stage: "Discovery",
    probability: 30,
    nextAction: "Send proposal",
    dueDate: "2026-08-25",
  },
  {
    id: 5,
    clientName: "Patricia Moore",
    value: 900000,
    product: "Trust Account",
    stage: "Closed Won",
    probability: 100,
    nextAction: "Onboarding",
    dueDate: "2026-08-17",
  },
  {
    id: 6,
    clientName: "Tom Bachmann",
    value: 120000,
    product: "Brokerage",
    stage: "Closed Lost",
    probability: 0,
    nextAction: "—",
    dueDate: "2026-08-10",
  },
];

export const RISK_COLORS = {
  Conservative: "bg-blue-100 text-blue-800",
  Growth: "bg-emerald-100 text-emerald-800",
  Aggressive: "bg-orange-100 text-orange-800",
};

export const PIPELINE_STAGES = ["Discovery", "Proposal", "Negotiation", "Closed Won", "Closed Lost"];
